### ISSUE TITLE
GitHub Stale Action Broken

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#150]
### Describe the issue

More of a repo issue but I noticed last night that there was an issue which should have been marked stale but it wasn't. Looking at the action list it shows that it's been trying to mark it as stale but hasn't been able to because it's getting `Resource not accessible by integration`. The lock action is also getting the same issue.

Seems like it might be a permissions error which which I cannot fix but this link should help solve the issue https://github.com/orgs/community/discussions/60820

This would also be an issue on the API repo.

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I also noticed that the validate is getting a warning due to the current version of checkout. I can create a PR to update it but it probably should be kept up-to-date automatically so I added dependabot to keep things updated.

I can merge in that PR if you want and you can take care of any python dependencies which shouldn't be many since the repo doesn't depend on many modules.

**Comment by cloneofghosts** [comment]
@alexander0042 The lock action seems to have been broken since January 27th. Not sure what happened but the error message is `Resource not accessible by personal access token`

**Comment by cloneofghosts** [comment]
I decided to just remove the lock action as it seems to not want to work correctly. I know other organizations have it working so it should be possible just not sure how atm.

**Comment by cloneofghosts** [comment]
Spoke too soon as things are still broken
