### ISSUE TITLE
Device Tracker 

### ISSUE THREAD

**Issue by alpha520098** [Pirate-Weather/pirate-weather-ha#295]
### Describe the feature

It would be nice if there was a entity that could take the in the distance and the bearing so this could be plotted onto a map:

so you could see excatly where the heading and the distance would be. 

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.

**Comment by dxmnkd316** [comment]
This is a really clever idea.  I know it can be in bad form to do this, but I really like this and would like to see this at some point.

One thing to consider is capping the number to the nearest 10 storms.  Or something like that.  But I would be happy with anything here.  

That said I wonder if there's a way to implement this using templates in HA Core.

**Comment by cloneofghosts** [comment]
Looks like this one got missed as well. Just to be clear you're looking to plot the distance/bearing on a graph to visualise which way a storm is heading?

I'm not totally sure what is 100% possible in HA so will defer to @alexander0042 to see if this would be possible

**Comment by dxmnkd316** [comment]
I assume that's what the OP is saying.

I think it would be one of those things where you'd use the device_tracker and map functionality.  You can give a device_tracker entity GPS coordinate


It could look something like this:
![image](https://github.com/user-attachments/assets/35d34ced-612a-4db7-9d94-fecd1637637b)
![image](https://github.com/user-attachments/assets/8287c660-8164-4b85-bfd0-98051f5eb3d1)
![image](https://github.com/user-attachments/assets/891bf3b7-dae0-429f-bba5-b9ac417103e5)

**Comment by alpha520098** [comment]
Spot on, this is exactly what is required.

**Comment by alexander0042** [comment]
Sorry for never replying to this, was focused on getting some critical historic data stuff working. The good news is that I got this working using the excellent [virtual devices add on](https://github.com/twrecked/hass-virtual)! I wrote it up as I was doing it, so let me track that down

**Comment by alexander0042** [comment]
Depending on how many locations you're trying call for at once, the default 15 minute call should fall well within the free tier, so hopefully that's ok! 

The way I got it working was to create a `virtual_tracker.yaml` file, which when loaded with that integration provides a virtual device that can move around to show the nearest storm on a map. The file is pretty basic, with these contents:

```
version: 1
devices: 
  Test Device_Tracker:
   - platform: device_tracker
```

Then, I made a new automation using this yaml:
```
alias: Storm Device Move
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.pirateweatherc_nearest_storm_distance
    trigger: state
  - entity_id:
      - sensor.pirateweatherc_nearest_storm_bearing
    trigger: state
conditions: []
actions:
  - variables:
      current_lat: "{{ state_attr('zone.home', 'latitude') | float * (pi / 180) }}"
      current_lon: "{{ state_attr('zone.home', 'longitude') | float * (pi / 180) }}"
      distance_km: "{{ states.sensor.pirateweatherc_nearest_storm_distance.state }}"
      direction_deg: "{{ states.sensor.pirateweatherc_nearest_storm_bearing.state }}"
      earth_radius_km: 6371
      direction_rad: "{{ direction_deg | float * (pi / 180) }}"
      new_lat: >-
        {{ (asin(sin(current_lat | float) * cos(distance_km/earth_radius_km) +
        cos(current_lat | float) * sin(distance_km/earth_radius_km) *
        cos(direction_rad))) * (180 / pi) }}
      new_lon: >-
        {{ (current_lon | float + atan2(sin(direction_rad) *
        sin(distance_km/earth_radius_km) * cos(current_lat | float),
        cos(distance_km/earth_radius_km) - sin(current_lat | float) *
        sin(new_lat))) * (180 / pi)  }}
  - target:
      entity_id: device_tracker.test_device_tracker
    data:
      gps:
        latitude: "{{ new_lat }}"
        longitude: "{{ new_lon }}"
    action: virtual.move
```

It assumes 
1. Your Pirate Weather integration is named "pirateweatherc".
2. The units for the integration are in si
3. Your device tracker is called "test_device_tracker"

The automation is triggered every time the nearest storm distance or bearing changes, and calls a service to update the location of the device tracker, giving me a map that looks like this:
![image](https://github.com/user-attachments/assets/99fb700f-53e2-4d0e-b65c-3dbcf9f2f1d5)

I'm very open to adding this directly into the integration somehow; however, it would be a little bit of work. The data is definitely there, but because device trackers [look reasonably complex](https://github.com/twrecked/hass-virtual/blob/498e3749cf61a697a52b420d8b8b6fc3e9ddbebb/custom_components/virtual/device_tracker.py), it's not a trivial thing.

**Comment by dxmnkd316** [comment]
nice work!

I'll be traveling for work this week so i'll have some downtime in the hotel to take a look this week hopefully.

**Comment by dxmnkd316** [comment]
I haven't had any chance to test this yet.  Hoping to get around to this and a couple other things in the next few weeks.
