### ISSUE TITLE
Migrate away from forecastio python library

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#324]
### Describe the issue

As mentioned in #321 it's probably time to migrate away from using the old forecastio python library as it hasn't been updated in about 6y and is prone to breaking in new python versions.

I'm not super familiar with HA so am not sure if we can just add in the models.py file into the integration and use that. I took a look at some official integrations and all of them seem to use an external library. Which means we may still need a library if you're planning to submit this as an official integration eventually.

If we still need a library to use then the options are

- Use the pirate-weather-python library linked in that issue
- Fork the forecastio library and use that fork instead (I have a fork here https://github.com/cloneofghosts/python-pirate-weather and am willing to add it to the organisation/invite you as a collaborator if you want)

I know the plan at one point was to re-write the integration using that library but the branch hasn't been updated in about a year so probably isn't the plan anymore.

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
It's things like this that really show the limits to my computer science knowledge. I sort of understand the whole async/ sync stuff, and appreciate how to use modules and the like, but I'm really not comfortable with it. 

For HA, it's both easiest and best (in the short term at least) to just drop the requirement and add the models.py script. It has very few dependencies, and really just organizes the response. We could even modify the sensors.py script to just use the json directly (like we do for the new fire sensor), but I like the idea of keeping some structure to it. Fewer dependencies is always better, and while I suspect there's some sort of benefit we could get from using a designated library, I don't know what it would be. PR with the change is coming momentarily. 

However, for other projects, a Python library that makes calls and whatnot probably makes sense! I'm going to try to reach out to @bakobako to see if he'd be ok with moving that library into the project, and building off it from there, since it seems like a great start!

**Comment by cloneofghosts** [comment]
Sure we can do that for the short-term and the integration will eventually switch over to using that library? I'll keep mine around in case it'll be useful for someone in the future.

**Comment by alexander0042** [comment]
Yes, agreed! You've very much convinced me on that point. just made the initial push with the library changes, with the fire risk level next

**Comment by cloneofghosts** [comment]
Okay, sounds good. When it's ready to test you can make a PR and assign me to review to check to make sure everything still works before going live.

Again, not really sure what the policy is for HA integrations is so not sure if you'd need to maintain a separate library or if you can include it in integration.

**Comment by cloneofghosts** [comment]
Fixed up the lint errors though in the models.py file I added placeholder comments so it would at least lint but need to be changed. Also there's an instance of OpenWeatherMap in one of the files that'll need to be changed. Also had to create a function for the fire index since it was complaining about complexity.

Did a quick test and it seems to work though after I added the fire index sensor the fire index level sensor wasn't added and I see no way to select it.

**Comment by bakobako** [comment]
@alexander0042 Just responding to the tag, I haven't worked on that code in a long time and don't plan to in the future since I no longer use it. Feel free to copy or modify anything you need. If you'd prefer, I can also delete the repo to avoid confusion if it's outdated. Just let me know.

**Comment by alexander0042** [comment]
Thanks for responding so quickly! What I'm planning on doing is forking it into our own organization, that way everything is in one place, but people can still trace the history back to your starting point!

**Comment by alexander0042** [comment]
Link for future reference: https://github.com/Pirate-Weather/pirate-weather-python

**Comment by cloneofghosts** [comment]
> Link for future reference: https://github.com/Pirate-Weather/pirate-weather-python

I'll setup dependabot, lint action and codeql and create a PR to merge it in or if you invite me to the repo I can merge it myself. @alexander0042 I also noticed you didn't merge in the changes you made on your branch a while back but maybe you just forgot about it.

**Comment by cloneofghosts** [comment]
@alexander0042 I know its a bit late for this but it may be helpful in the future but I published my forecastio fork on PyPI yesterday https://pypi.org/project/python-pirateweather/
